--==============================================================================
-- Global Defines
--==============================================================================

_DEBUG = false
local printFailMessage = false


--==============================================================================
-- Dependency
--==============================================================================

require "lib/util"
local Lexical       = require "src/lexical"
local Syntactic     = require "src/syntactic"
local Semantic      = require "src/semantic"
local InterCodeGen  = require "src/intermediate_code"


--==============================================================================
-- Data Structure
--==============================================================================

local files = {
  {
    name      = "nil_file",
    open      = false,
  },
  {
    name      = "lex_fail",
    open      = true,
    lexical   = false,
  },
  {
    name      = "lex_overload_01",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "lex_overload_02",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "lex_overload_03",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "lex_overload_04",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "sem_complete_program",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "sem_elseif_block",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "sem_fail_attrib_string_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_attrib_char_string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_attrib_int_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_call_not_function",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_call_wrong_param_number",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_declare_same_name_01",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_declare_same_name_02",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  }, 
  {
    name      = "sem_fail_elseif_condition",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_exp_negate_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_exp_sum_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_exp_unary_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_func_ret_dimension_different",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_func_ret_nil",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_func_ret_type_different",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_func_same_par_name",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_func_void_return",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "sem_fail_if_condition_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_var_array_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_var_array_dimension_zero",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_var_array_larger",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_var_existent",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "sem_fail_var_undeclared",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },

  -- ITERATION 3
  {
    name      = "00-fail-empty",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "01-global",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "02-fun",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "03-nls",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "04-funglobal",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "05-params",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "06-declvar",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "07-if",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "08-fail-else",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "09-fail-elseif",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "10-fail-if",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "11-ifdecl",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "12-while",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "13-fail-while",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "14-ifwhile",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "15-fail-ifwhile",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "16-atrib",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "17-call",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "18-fail-call",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "19-callargs",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "19-fail-callargs",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "20-return",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "21-arrays",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "21-return-noargs",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "22-exp",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "22-fail-exp",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "23-fail-fun",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "24-fail-fun2",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "25-fail-fun3",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "26-fail-fun4",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "27-fail-global",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "28-fail-block",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "29-fail-params",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "30-fail-param",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "31-fail-type",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "32-fail-declvar",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "33-fail-missingexp",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "34-fail-invalidexp",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "35-expprio",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "36-fail-roottoken",
    open      = true,
    lexical   = true,
    syntactic = false,
  },
  {
    name      = "37-invprio",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },

  -- ITERATION 4
  {
    name      = "01-fail-fun",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "02-fail-argtype",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "03-fail-argcount",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "04-fail-void",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "05-void2",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "06-fail-global",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "07-globalok",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "08-global-as-arg",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "09-fail-undecl",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "10-fail-undecl-fn",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "11-fail-redecl-arg",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "12-fail-redecl-arg2",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "13-fail-redecl-arg3",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "14-fail-redecl-arg4",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "15-assign",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "16-return-var",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "17-if",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "18-fail-if",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "19-fail-elseif",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "20-fail-while",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "21-while",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "22-exp-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "23-exp-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "24-call",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "25-eqvect",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "26-exp-boolidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "27-exp-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "28-expcall",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "29-exp-intchar2",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "30-exp-intcharidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "31-exp-intchar",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "32-fail-litbool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "33-fail-litnum",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "34-fail-litstring",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "35-fail-new",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "36-fail-rel2",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "37-fail-rel",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "38-new",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "39-rel",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "40-return",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "41-scope-argvsglobal",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "42-scope-localvsglobal",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "43-scope-localvslocal",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "44-fail-global-redec",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "45-fail-fun-redec",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "100-int-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "101-int-int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "102-int-int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "103-int-int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "104-int-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "105-int-char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "106-int-char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "107-int-char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "108-fail-int-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "109-fail-int-bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "110-fail-int-bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "111-fail-int-bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "112-fail-int-string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "113-fail-int-string-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "114-fail-int-string-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "115-fail-int-string-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "116-fail-int-v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "117-fail-int-v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "118-fail-int-v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "119-fail-int-v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "120-fail-int-v_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "121-fail-int-v_char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "122-fail-int-v_char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "123-fail-int-v_char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "124-fail-int-v_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "125-fail-int-v_bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "126-fail-int-v_bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "127-fail-int-v_bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "128-fail-int-v_v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "129-fail-int-v_v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "130-fail-int-v_v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "131-fail-int-v_v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "132-char-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "133-char-int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "134-char-int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "135-char-int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "136-char-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "137-char-char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "138-char-char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "139-char-char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "140-fail-char-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "141-fail-char-bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "142-fail-char-bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "143-fail-char-bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "144-fail-char-string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "145-fail-char-string-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "146-fail-char-string-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "147-fail-char-string-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "148-fail-char-v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "149-fail-char-v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "150-fail-char-v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "151-fail-char-v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "152-fail-char-v_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "153-fail-char-v_char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "154-fail-char-v_char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "155-fail-char-v_char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "156-fail-char-v_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "157-fail-char-v_bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "158-fail-char-v_bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "159-fail-char-v_bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "160-fail-char-v_v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "161-fail-char-v_v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "162-fail-char-v_v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "163-fail-char-v_v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "164-fail-bool-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "165-fail-bool-int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "166-fail-bool-int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "167-fail-bool-int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "168-fail-bool-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "169-fail-bool-char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "170-fail-bool-char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "171-fail-bool-char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "172-bool-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "173-bool-bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "174-bool-bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "175-bool-bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "176-fail-bool-string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "177-fail-bool-string-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "178-fail-bool-string-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "179-fail-bool-string-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "180-fail-bool-v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "181-fail-bool-v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "182-fail-bool-v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "183-fail-bool-v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "184-fail-bool-v_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "185-fail-bool-v_char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "186-fail-bool-v_char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "187-fail-bool-v_char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "188-fail-bool-v_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "189-fail-bool-v_bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "190-fail-bool-v_bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "191-fail-bool-v_bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "192-fail-bool-v_v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "193-fail-bool-v_v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "194-fail-bool-v_v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "195-fail-bool-v_v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "196-fail-string-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "197-fail-string-int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "198-fail-string-int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "199-fail-string-int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "200-fail-string-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "201-fail-string-char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "202-fail-string-char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "203-fail-string-char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "204-fail-string-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "205-fail-string-bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "206-fail-string-bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "207-fail-string-bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "208-string-string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "209-string-string-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "210-string-string-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "211-string-string-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "212-fail-string-v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "213-fail-string-v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "214-fail-string-v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "215-fail-string-v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "216-string-v_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "217-string-v_char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "218-string-v_char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "219-string-v_char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "220-fail-string-v_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "221-fail-string-v_bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "222-fail-string-v_bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "223-fail-string-v_bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "224-fail-string-v_v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "225-fail-string-v_v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "226-fail-string-v_v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "227-fail-string-v_v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "228-fail-v_int-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "229-fail-v_int-int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "230-fail-v_int-int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "231-fail-v_int-int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "232-fail-v_int-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "233-fail-v_int-char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "234-fail-v_int-char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "235-fail-v_int-char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "236-fail-v_int-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "237-fail-v_int-bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "238-fail-v_int-bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "239-fail-v_int-bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "240-fail-v_int-string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "241-fail-v_int-string-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "242-fail-v_int-string-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "243-fail-v_int-string-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "244-v_int-v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "245-v_int-v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "246-v_int-v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "247-v_int-v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "248-fail-v_int-v_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "249-fail-v_int-v_char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "250-fail-v_int-v_char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "251-fail-v_int-v_char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "252-fail-v_int-v_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "253-fail-v_int-v_bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "254-fail-v_int-v_bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "255-fail-v_int-v_bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "256-fail-v_int-v_v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "257-fail-v_int-v_v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "258-fail-v_int-v_v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "259-fail-v_int-v_v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "260-fail-v_char-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "261-fail-v_char-int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "262-fail-v_char-int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "263-fail-v_char-int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "264-fail-v_char-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "265-fail-v_char-char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "266-fail-v_char-char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "267-fail-v_char-char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "268-fail-v_char-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "269-fail-v_char-bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "270-fail-v_char-bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "271-fail-v_char-bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "272-v_char-string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "273-v_char-string-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "274-v_char-string-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "275-v_char-string-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "276-fail-v_char-v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "277-fail-v_char-v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "278-fail-v_char-v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "279-fail-v_char-v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "280-v_char-v_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "281-v_char-v_char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "282-v_char-v_char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "283-v_char-v_char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "284-fail-v_char-v_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "285-fail-v_char-v_bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "286-fail-v_char-v_bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "287-fail-v_char-v_bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "288-fail-v_char-v_v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "289-fail-v_char-v_v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "290-fail-v_char-v_v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "291-fail-v_char-v_v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "292-fail-v_bool-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "293-fail-v_bool-int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "294-fail-v_bool-int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "295-fail-v_bool-int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "296-fail-v_bool-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "297-fail-v_bool-char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "298-fail-v_bool-char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "299-fail-v_bool-char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "300-fail-v_bool-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "301-fail-v_bool-bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "302-fail-v_bool-bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "303-fail-v_bool-bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "304-fail-v_bool-string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "305-fail-v_bool-string-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "306-fail-v_bool-string-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "307-fail-v_bool-string-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "308-fail-v_bool-v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "309-fail-v_bool-v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "310-fail-v_bool-v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "311-fail-v_bool-v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "312-fail-v_bool-v_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "313-fail-v_bool-v_char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "314-fail-v_bool-v_char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "315-fail-v_bool-v_char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "316-v_bool-v_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "317-v_bool-v_bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "318-v_bool-v_bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "319-v_bool-v_bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "320-fail-v_bool-v_v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "321-fail-v_bool-v_v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "322-fail-v_bool-v_v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "323-fail-v_bool-v_v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "324-fail-v_v_int-int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "325-fail-v_v_int-int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "326-fail-v_v_int-int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "327-fail-v_v_int-int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "328-fail-v_v_int-char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "329-fail-v_v_int-char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "330-fail-v_v_int-char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "331-fail-v_v_int-char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "332-fail-v_v_int-bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "333-fail-v_v_int-bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "334-fail-v_v_int-bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "335-fail-v_v_int-bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "336-fail-v_v_int-string",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "337-fail-v_v_int-string-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "338-fail-v_v_int-string-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "339-fail-v_v_int-string-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "340-fail-v_v_int-v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "341-fail-v_v_int-v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "342-fail-v_v_int-v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "343-fail-v_v_int-v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "344-fail-v_v_int-v_char",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "345-fail-v_v_int-v_char-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "346-fail-v_v_int-v_char-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "347-fail-v_v_int-v_char-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "348-fail-v_v_int-v_bool",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "349-fail-v_v_int-v_bool-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "350-fail-v_v_int-v_bool-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "351-fail-v_v_int-v_bool-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = false,
  },
  {
    name      = "352-v_v_int-v_v_int",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "353-v_v_int-v_v_int-ret",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "354-v_v_int-v_v_int-retglob",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
  {
    name      = "355-v_v_int-v_v_int-retidx",
    open      = true,
    lexical   = true,
    syntactic = true,
    semantic  = true,
  },
}


--==============================================================================
-- Private Methods
--==============================================================================

local function Run ()
  local num_files = 0
  local num_files_read = 1
  for _, _ in pairs (files) do
    num_files = num_files + 1
  end
  for _, valid in ipairs (files) do
    local file_str                  --  keeps the convertion of file to string
    local unexpected_error = false  --  inform that an unexpected error occurs (if true stop further tests)
    local expected_error = false    --  inform that an expected error occurs (if true stop further tests)
    local ok, msg

    -- TEST OPENING
    ------------------------------------------------
    if (not unexpected_error and not expected_error) then
      local f = io.open("data/" .. valid.name .. ".txt", "r")
      if (not f and valid.open) then
        unexpected_error = true
        print(string.format('(%3s de %3s) FAILURE - File "%s" expected to open.', num_files_read, num_files, valid.name))
      elseif (f and not valid.open) then
        unexpected_error = true
        print(string.format('(%3s de %3s) FAILURE - File "%s" not expected to open.', num_files_read, num_files, valid.name))
      elseif (not f and not valid.open) then
        expected_error = true
        msg = "@0 file error: could not be opened."
      else
        file_str = f:read("*a")
        f:close()
      end
    end
    
    -- TEST LEXICAL
    ------------------------------------------------
    if (not unexpected_error and not expected_error) then
      ok, msg = Lexical.Open(file_str)
      if (not ok and valid.lexical) then
        unexpected_error = true
        print(string.format('(%3s de %3s) FAILURE - File "%s" expected to PASS on lexical. \n\t %s', num_files_read, num_files, valid.name, msg or ""))
      elseif (ok and not valid.lexical) then
        unexpected_error = true
        print(string.format('(%3s de %3s) FAILURE - File "%s" expected to FAIL on lexical. \n\t %s', num_files_read, num_files, valid.name, msg or ""))
      elseif (not ok and not valid.lexical) then
        expected_error = true
      end
    end
    
    -- TEST SYNTAX
    ------------------------------------------------
    if (not unexpected_error and not expected_error) then
      ok, msg = Syntactic.Open(Lexical.GetTags())
      if (not ok and valid.syntactic) then
        unexpected_error = true
        print(string.format('(%3s de %3s) FAILURE - File "%s" expected to PASS on syntactic. \n\t %s', num_files_read, num_files, valid.name, msg or ""))
      elseif (ok and not valid.syntactic) then
        unexpected_error = true
        print(string.format('(%3s de %3s) FAILURE - File "%s" expected to FAIL on syntactic. \n\t %s', num_files_read, num_files, valid.name, msg or ""))
      elseif (not ok and not valid.syntactic) then
        expected_error = true
      end
    end
    
    -- TEST SEMANTIC
    ------------------------------------------------
    if (not unexpected_error and not expected_error) then
      ok, msg = Semantic.Open(Syntactic.GetTree())
      if (not ok and valid.semantic) then
        unexpected_error = true
        print(string.format('(%3s de %3s) FAILURE - File "%s" expected to PASS on semantic. \n\t %s', num_files_read, num_files, valid.name, msg or ""))
      elseif (ok and not valid.semantic) then
        unexpected_error = true
        print(string.format('(%3s de %3s) FAILURE - File "%s" expected to FAIL on semantic. \n\t %s', num_files_read, num_files, valid.name, msg or ""))
      elseif (not ok and not valid.semantic) then
        expected_error = true
      end
    end

    -- TEST INTERMEDIATE CODE GENERATOR
    ------------------------------------------------
    if (not unexpected_error and not expected_error) then
      ok, msg = InterCodeGen.Open("out/" .. valid.name, Semantic.GetTree())
      if (not ok) then
        print(string.format('(%3s de %3s) FAILURE - Unexpected error while writing intermediate code. \n\t', num_files_read, num_files))
      end
    end

    -- PASSED ALL TESTS
    ------------------------------------------------
    if (not unexpected_error or expected_error) then
      print(string.format('(%3s de %3s) SUCCESS - File "%s".', num_files_read, num_files, valid.name))
      if (expected_error and printFailMessage) then
        print("        ", msg)
      end
    end
    num_files_read = num_files_read + 1
  end
end


--==============================================================================
-- Running
--==============================================================================

local ok, msg = pcall(function () Run() end)
if (not ok) then
  print("Erro inesperado no teste automático. " .. msg)
end